export const notifications = [{
        id: 1,
        sender: "Le Nguyen Phuc Nhan",
        message: "Ms. Nhan gave feedback for study-plan",
        type: "feedback",
        time: "8:25 am",
        read: false,
    },
    {
        id: 2,
        sender: "System",
        message: "Your semester goals have been auto-saved.",
        type: "system",
        time: "8:00 am",
        read: true,
    },
    {
        id: 3,
        sender: "Deadline Reminder",
        message: "Update your study plan before 5PM today.",
        type: "reminder",
        time: "7:45 am",
        read: false,
    },
    {
        id: 4,
        sender: "Ms. Nhan",
        message: "Feedback received: Please adjust your target score.",
        type: "feedback",
        time: "7:30 am",
        read: true,
    },
    {
        id: 5,
        sender: "System",
        message: "New academic schedule is available.",
        type: "system",
        time: "7:15 am",
        read: false,
    },
    {
        id: 6,
        sender: "Le Nguyen Phuc Nhan",
        message: "Reminder: Submit your weekly progress report.",
        type: "reminder",
        time: "7:00 am",
        read: false,
    },
];